wip: trying to run on new NAS boxes

diff --git a/bin/talos-disk-overwrite b/bin/talos-disk-overwrite
--- a/bin/talos-disk-overwrite
+++ b/bin/talos-disk-overwrite
@@ -4,9 +4,32 @@ test -z "${DEBUG:-}" || set -x
 test -n "${PRJ_ROOT:-}" || eval "$(cd "${BASH_SOURCE[0]%/*}" && direnv export bash)"
 
 disk="$1"
-image="${2:-"default"}"
-url="$(talos-image install "${image}")"
+node_name="${2}"
+node="$(name="${node_name}" talos-cfg -cM '.nodes[env.name]')"
+schematic="$(jq -r .image.schematic <<<"$node")"
+url="$(talos-image "${node_name}" install)"
 version="$(talos-cfg -r .talos.version)"
-out="${PRJ_ROOT}/talos-${version}/${image}.metal-arm64.raw.xz"
+filename="${url##*/}"
+out="${PRJ_CACHE_HOME}/talos/v${version}/${schematic}.${filename}"
+mkdir -p "${out%/*}"
 test -e "$out" || curl --fail "${url}" -o "$out"
-xz -d --stdout "$out" | sudo dd if=/dev/stdin conv=fsync bs=4M status=progress of="${disk}"
+
+unpack() {
+  case "$out" in
+  *.zst)
+    unzstd --stdout "$out"
+    ;;
+  *.iso)
+    cat "$out"
+    ;;
+  *.xz)
+    xz -d --stdout "$out"
+    ;;
+  *)
+    echo "ERROR: invalid file extension $out" >&2
+    exit 1
+    ;;
+  esac
+}
+
+unpack | sudo dd if=/dev/stdin conv=fsync bs=4M status=progress of="${disk}"
diff --git a/bin/talos-image b/bin/talos-image
--- a/bin/talos-image
+++ b/bin/talos-image
@@ -3,14 +3,37 @@ set -eEuo pipefail
 test -z "${DEBUG:-}" || set -x
 test -n "${PRJ_ROOT:-}" || eval "$(cd "${BASH_SOURCE[0]%/*}" && direnv export bash)"
 
-action="${1:-upgrade}"
-name="${2:-default}"
-spec="${PRJ_ROOT}/image-schematics/${name}.yaml"
+node="$(name="${1}" talos-cfg -cM '.nodes[env.name]')"
+action="${2:-upgrade}"
+type="${3:-"$(jq -r '.image.type // "raw"' <<<"$node")"}"
+secure_boot="$(jq -r '.image["secure-boot"]' <<<"$node")"
+arch="$(jq -r '.image.arch' <<<"$node")"
+platform="$(jq -r '.image.platform // "metal"' <<<"$node")"
+schematic="$(jq -r '.image.schematic' <<<"$node")"
+spec="${PRJ_ROOT}/image-schematics/${schematic}.yaml"
 
 id="$(curl --silent --fail -X POST --data-binary "@${spec}" https://factory.talos.dev/schematics | jq -r .id)"
 version="$(talos-cfg -r .talos.version)"
-upgrade_url="factory.talos.dev/installer/${id}:v${version}"
-install_url="https://factory.talos.dev/image/${id}/v${version}/metal-arm64.raw.xz"
+base_install_url="https://factory.talos.dev/image/${id}/v${version}"
+
+secureboot_suffix=""
+if test "${secure_boot}" == "true"; then
+  secureboot_suffix="-secureboot"
+fi
+
+upgrade_url="factory.talos.dev/installer${secureboot_suffix}/${id}:v${version}"
+case "${type}" in
+iso)
+  install_url="${base_install_url}/${platform}-${arch}${secureboot_suffix}.iso"
+  ;;
+raw)
+  install_url="${base_install_url}/${platform}-${arch}${secureboot_suffix}.raw.zst"
+  ;;
+*)
+  echo "ERROR: invalid imagu type ${type}" >&2
+  exit 1
+  ;;
+esac
 
 case "${action}" in
 upgrade)
